Request to review the code of new MF Test cases
MoolyaSoftwareTesting/Kuvera_RF pull request #29
Opened 2021-09-02 07:33 UTC by sayantanigoswami1996

2021-09-02 08:00 UTC, shantanu-kuvera requested changes

2021-09-02 08:00 UTC, shantanu-kuvera commented on AppLocators/DesktopWeb/PostLoginFlowsLocators/MutualFunds/PortfolioMFLocators.robot
> +${KU_W_portfolio_mf_totalVal} =  xpath=//*[@class='b-cumulative-fund-row__total-value-rs-data']
Avoid using * as it searches the entire dom for the element. Use tags instead. 
Remove * for element search from the entire file.

2021-09-02 08:00 UTC, shantanu-kuvera commented on AppLocators/DesktopWeb/PostLoginFlowsLocators/MutualFunds/PortfolioMFLocators.robot
> +${KU_W_portfolio_mf_value} =  xpath=//div[@class='b-portfolio-tab__value b-portfolio-tab__value--selected']
Avoid using class as the attribute when there is a compounded string. Please check whether some other attribute can be incorporated here.

2021-09-06 10:49 UTC, sayantanigoswami1996 commented on AppLocators/DesktopWeb/PostLoginFlowsLocators/MutualFunds/PortfolioMFLocators.robot
> +${KU_W_portfolio_mf_totalVal} =  xpath=//*[@class='b-cumulative-fund-row__total-value-rs-data']
This has been fixed . The * has been replaced with respective tags.

2021-09-06 10:50 UTC, sayantanigoswami1996 commented on AppLocators/DesktopWeb/PostLoginFlowsLocators/MutualFunds/PortfolioMFLocators.robot
> +${KU_W_portfolio_mf_value} =  xpath=//div[@class='b-portfolio-tab__value b-portfolio-tab__value--selected']
As discussed , this has been understood from the two solutions which has been given by you . Henceforth , will be taken care of when freshly coded. Old codebase can be changed later.

2021-09-06 10:56 UTC, PrathijaEtagi commented on AppLocators/DesktopWeb/PostLoginFlowsLocators/MutualFunds/PortfolioMFLocators.robot
> +${KU_W_portfolio_mf_totalVal} =  xpath=//*[@class='b-cumulative-fund-row__total-value-rs-data']
Fixed

2021-09-06 11:08 UTC, PrathijaEtagi commented on AppLocators/DesktopWeb/PostLoginFlowsLocators/MutualFunds/PortfolioMFLocators.robot
> +${KU_W_portfolio_mf_value} =  xpath=//div[@class='b-portfolio-tab__value b-portfolio-tab__value--selected']
Looks fine

2021-09-06 11:11 UTC, PrathijaEtagi approved these changes
Approved

2021-09-06 11:22 UTC, closed without merging

2021-09-06 11:22 UTC, sayantanigoswami1996 commented
> Approved, Take care of confilts.

Yes.